### ISSUE TITLE
Awesome extension

### ISSUE THREAD

**Issue by biati-digital** [aaronbushnell/nova-rebound-delete#1]
Thank you for this extension, I hate the way nova handles cmd+backspace, this extension solves this problem, just two questions:

1.- Why is the activationEvents set to "onLanguage:javascript"
2.- By the fault the extension does nothing unless you configure a keybinding in nova preferences, is there any reason to not specify the shortcode in the extension? for example:

```json
"editor": [
  {
    "title": "Delete Line using Rebound",
    "command": "rebound-delete.reboundDelete",
    "when": "editorHasFocus",
    "shortcut": "cmd-backspace"
  }
]
```

Anyway, really useful extension.

**Comment by aaronbushnell** [comment]
Hey, @biati-digital!

1. Looks like this got added into the extension when I followed Panic's "Create new extension..." wizard. This is now removed!
2. I had no idea about this! This is added!
